[package]
name = "kernel_filtering"
version = "0.1.0"
authors = ["galoz <gal.oz@powtoon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18.1"
image = "0.22.2"